// Handgeschriebene Posts. Typen: fakt, tipp, mythos, rechnung.
// Bei "mythos" ist `title` der Irrglaube und `body` die Richtigstellung.
// *Text in Sternchen* wird im Bild farbig hervorgehoben.
// Bewusst zeitlose Inhalte ohne Beträge, die sich jährlich ändern (Freibeträge usw.).

export const POSTS = [
  {
    id: 'pay-yourself-first',
    type: 'tipp',
    title: 'Zahl dich zuerst selbst',
    body: 'Richte einen Dauerauftrag ein, der *direkt nach dem Gehaltseingang* Geld aufs Sparkonto oder in deinen Sparplan schiebt.\nWas du nicht siehst, gibst du nicht aus.',
  },
  {
    id: 'notgroschen',
    type: 'tipp',
    title: 'Erst der Notgroschen, dann investieren',
    body: 'Eine häufige Faustregel: *3 bis 6 Monatsausgaben* als Reserve auf einem Tagesgeldkonto.\nSo musst du bei einer kaputten Waschmaschine keinen Kredit aufnehmen – und keine Aktien im falschen Moment verkaufen.',
  },
  {
    id: 'einlagensicherung',
    type: 'fakt',
    title: 'Dein Geld auf der Bank ist abgesichert',
    body: 'In der EU sind Einlagen durch die gesetzliche Einlagensicherung bis *100.000 € pro Kunde und Bank* geschützt.\nDas gilt für Girokonto, Tagesgeld und Festgeld.',
  },
  {
    id: 'etf-sondervermoegen',
    type: 'fakt',
    title: 'Was passiert mit deinem ETF, wenn der Anbieter pleitegeht?',
    body: 'Fondsvermögen ist *Sondervermögen*. Es wird getrennt vom Vermögen der Fondsgesellschaft verwahrt und fällt bei einer Pleite nicht in die Insolvenzmasse.\nDas Kursrisiko trägst du trotzdem selbst.',
  },
  {
    id: 'mythos-viel-geld',
    type: 'mythos',
    title: '„Zum Investieren brauchst du viel Geld.“',
    body: 'Viele Broker bieten Sparpläne schon ab *wenigen Euro im Monat* an.\nWichtiger als der Betrag ist, früh anzufangen und dranzubleiben.',
  },
  {
    id: 'mythos-gluecksspiel',
    type: 'mythos',
    title: '„Aktien sind wie Glücksspiel.“',
    body: 'Einzelne Aktien können stark schwanken. Wer aber *breit gestreut* über viele Länder und Unternehmen und *langfristig* anlegt, hat historisch Wertzuwächse erzielt.\nEine Garantie gibt es trotzdem nicht.',
  },
  {
    id: '50-30-20',
    type: 'tipp',
    title: 'Die 50/30/20-Regel',
    body: '*50 %* deines Nettos für Fixkosten wie Miete und Handy.\n*30 %* für Dinge, die Spaß machen.\n*20 %* zum Sparen und Investieren.\nKeine Pflicht – aber ein guter Startpunkt.',
  },
  {
    id: 'brutto-netto',
    type: 'fakt',
    title: 'Brutto ist nicht Netto',
    body: 'Von deinem Bruttogehalt gehen noch *Sozialversicherung* und eventuell *Lohnsteuer* ab.\nPlane immer mit dem Betrag, der wirklich auf deinem Konto ankommt.',
  },
  {
    id: 'vl',
    type: 'tipp',
    title: 'Frag nach Vermögenswirksamen Leistungen',
    body: 'Viele Arbeitgeber zahlen – oft durch Tarifvertrag geregelt – *zusätzliches Geld* für deinen Vermögensaufbau, auch an Azubis.\nFrag in der Personalabteilung nach. Sonst verschenkst du es.',
  },
  {
    id: 'steuererklaerung-azubi',
    type: 'tipp',
    title: 'Steuererklärung als Azubi?',
    body: 'Wurde dir Lohnsteuer abgezogen, kann sich eine *freiwillige Steuererklärung* lohnen – zum Beispiel wegen Fahrtkosten oder Arbeitsmitteln.\nDu hast dafür bis zu *4 Jahre rückwirkend* Zeit.',
  },
  {
    id: 'freistellungsauftrag',
    type: 'tipp',
    title: 'Freistellungsauftrag nicht vergessen',
    body: 'Ohne Freistellungsauftrag zieht deine Bank auf Zinsen und Kursgewinne sofort Steuern ab.\nMit Freistellungsauftrag bleiben Erträge bis zum *Sparer-Pauschbetrag* steuerfrei. Dauert 2 Minuten im Onlinebanking.',
  },
  {
    id: 'abgeltungsteuer',
    type: 'fakt',
    title: 'So werden Kapitalerträge besteuert',
    body: 'Zinsen, Dividenden und Kursgewinne unterliegen der *Abgeltungsteuer von 25 %* plus Solidaritätszuschlag und ggf. Kirchensteuer.\nErst oberhalb des Sparer-Pauschbetrags.',
  },
  {
    id: 'dispo',
    type: 'fakt',
    title: 'Der Dispo ist ein teurer Kredit',
    body: 'Der Dispokredit gehört zu den *teuersten Krediten*, die es gibt.\nWenn du regelmäßig im Minus bist: Ausgaben prüfen und das Minus gezielt abbauen.',
  },
  {
    id: 'schufa-auskunft',
    type: 'fakt',
    title: 'Deine Schufa-Daten kostenlos einsehen',
    body: 'Nach *Art. 15 DSGVO* hast du Anspruch auf eine kostenlose Kopie deiner gespeicherten Daten.\nFalsche Einträge kannst du berichtigen lassen.',
  },
  {
    id: 'mythos-zinsen-sparbuch',
    type: 'mythos',
    title: '„Auf dem Sparbuch ist mein Geld sicher.“',
    body: 'Vor einer Pleite der Bank: ja. Vor *Inflation*: nein.\nLiegen die Zinsen unter der Inflationsrate, verliert dein Geld jedes Jahr an Kaufkraft.',
  },
  {
    id: 'lifestyle-inflation',
    type: 'tipp',
    title: 'Vorsicht vor Lifestyle-Inflation',
    body: 'Mehr Gehalt nach der Ausbildung? Super.\nAber wenn die Ausgaben genauso schnell steigen, bleibt am Ende nichts übrig. Tipp: *Die Hälfte jeder Gehaltserhöhung* direkt sparen.',
  },
  {
    id: 'diversifikation',
    type: 'fakt',
    title: 'Nicht alle Eier in einen Korb',
    body: 'Streuung heißt: Dein Geld auf *viele Unternehmen, Branchen und Länder* verteilen.\nGeht eine Firma pleite, ist nicht gleich alles weg.',
  },
  {
    id: 'etf-erklaert',
    type: 'fakt',
    title: 'Was ist ein ETF?',
    body: 'Ein ETF ist ein *börsengehandelter Fonds*, der meist einen Index wie den MSCI World nachbildet.\nMit einem Kauf bist du an sehr vielen Unternehmen auf einmal beteiligt – meist zu geringen Kosten.',
  },
  {
    id: 'time-in-market',
    type: 'tipp',
    title: 'Zeit am Markt schlägt Timing',
    body: 'Den perfekten Einstiegszeitpunkt findet niemand zuverlässig.\nEin *regelmäßiger Sparplan* nimmt dir diese Entscheidung ab: Mal kaufst du teurer, mal günstiger.',
  },
  {
    id: 'debit-vs-kredit',
    type: 'fakt',
    title: 'Debitkarte oder Kreditkarte?',
    body: 'Bei der *Debitkarte* wird dein Konto sofort belastet.\nBei der *Kreditkarte* sammelt die Bank die Umsätze und bucht sie später ab. Wer die Rechnung nicht voll bezahlt, zahlt oft hohe Zinsen.',
  },
  {
    id: 'mythos-ratenkauf',
    type: 'mythos',
    title: '„0 % Finanzierung ist geschenktes Geld.“',
    body: 'Auch ohne Zinsen ist es ein *Kredit*. Er kann in deiner Schufa auftauchen und verleitet dazu, mehr zu kaufen, als du dir leisten kannst.\nLies immer das Kleingedruckte.',
  },
  {
    id: 'haushaltsbuch',
    type: 'tipp',
    title: '30 Tage alles aufschreiben',
    body: 'Notiere einen Monat lang *jede Ausgabe*.\nDie meisten sind überrascht, wie viel für Kleinkram wie Snacks, Lieferdienste und Abos draufgeht.',
  },
  {
    id: 'abos-pruefen',
    type: 'tipp',
    title: 'Check deine Abos',
    body: 'Streaming, Apps, Fitness, Zeitschriften …\nGeh einmal deine *Kontoauszüge* durch und kündige alles, was du seit Wochen nicht genutzt hast.',
  },
  {
    id: 'nettovermoegen',
    type: 'fakt',
    title: 'Dein Nettovermögen',
    body: '*Alles, was du besitzt, minus alle Schulden.*\nDiese eine Zahl zeigt dir besser als dein Gehalt, ob du finanziell vorankommst. Rechne sie einmal im Monat aus.',
  },
  {
    id: 'mythos-zu-jung',
    type: 'mythos',
    title: '„Ich bin zu jung, um mich um Geld zu kümmern.“',
    body: 'Gerade jung hast du den größten Vorteil: *Zeit*.\nJe früher du anfängst, desto länger arbeitet der Zinseszins für dich.',
  },
  {
    id: 'zinseszins-erklaert',
    type: 'fakt',
    title: 'Zinseszins einfach erklärt',
    body: 'Du bekommst nicht nur Zinsen auf dein eingezahltes Geld, sondern auch *Zinsen auf deine Zinsen*.\nAm Anfang merkt man das kaum. Nach vielen Jahren wird es zum stärksten Effekt beim Vermögensaufbau.',
  },
  {
    id: 'ter',
    type: 'fakt',
    title: 'Was bedeutet TER?',
    body: 'Die *Total Expense Ratio* zeigt die laufenden Kosten eines Fonds pro Jahr in Prozent.\nSie wird automatisch vom Fondsvermögen abgezogen – du siehst sie auf keiner Rechnung.',
  },
  {
    id: 'mythos-schulden',
    type: 'mythos',
    title: '„Schulden sind immer schlecht.“',
    body: 'Es kommt darauf an, *wofür*. Ein Kredit für etwas, das Wert schafft, ist etwas anderes als Konsum auf Pump.\nEntscheidend: Du kannst die Raten sicher zahlen.',
  },
  {
    id: 'girokonto-kosten',
    type: 'tipp',
    title: 'Was kostet dein Girokonto?',
    body: 'Kontoführung, Karte, Überweisungen – das kann sich im Jahr summieren.\nViele Banken bieten für *Azubis und Studierende* vergünstigte Konten an. Einfach nachfragen.',
  },
  {
    id: 'sparziel',
    type: 'tipp',
    title: 'Gib deinem Geld ein Ziel',
    body: '„Sparen“ ist abstrakt. „*Führerschein bis August*“ ist konkret.\nLeg für jedes Ziel ein eigenes Unterkonto an – so siehst du den Fortschritt.',
  },
  {
    id: 'mythos-gehalt',
    type: 'mythos',
    title: '„Mit mehr Gehalt bin ich automatisch reich.“',
    body: 'Reich wirst du nicht durch das, was du *verdienst*, sondern durch das, was du *behältst und anlegst*.\nEs gibt Gutverdiener ohne Vermögen und Normalverdiener mit viel Vermögen.',
  },
  {
    id: 'kuendigungsfrist-handy',
    type: 'tipp',
    title: 'Handyvertrag verlängert sich? Nicht mehr für ewig.',
    body: 'Nach Ablauf der Mindestlaufzeit kannst du Handy- und Internetverträge *mit einer Frist von einem Monat* kündigen – so regelt es das Telekommunikationsgesetz.\nZeit, den Tarif zu vergleichen.',
  },
  {
    id: 'einkommen-erhoehen',
    type: 'tipp',
    title: 'Sparen hat Grenzen, Verdienen nicht',
    body: 'Irgendwann kannst du nicht weiter sparen.\n*Weiterbildung, Nebenjob, Gehaltsverhandlung* – dein Einkommen zu steigern hat oft den größeren Hebel.',
  },
  {
    id: 'emotionen',
    type: 'tipp',
    title: 'Nicht panisch verkaufen',
    body: 'Kurse fallen immer wieder – manchmal stark.\nWer in Panik verkauft, macht *Verluste endgültig*. Geld, das du bald brauchst, gehört deshalb nicht in Aktien.',
  },
  {
    id: 'tagesgeld-festgeld',
    type: 'fakt',
    title: 'Tagesgeld oder Festgeld?',
    body: '*Tagesgeld*: jederzeit verfügbar, Zins kann sich ändern.\n*Festgeld*: fester Zins für eine feste Laufzeit, dafür kommst du vorher nicht ran.',
  },
];
